# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='question',
            new_name='eid',
        ),
    ]
