# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20160725_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='eid',
            new_name='events',
        ),
    ]
