# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_auto_20160725_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(verbose_name='events time'),
        ),
    ]
