# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0005_auto_20160725_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='events',
            new_name='event',
        ),
    ]
