# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0006_auto_20160725_1518'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together=set([('phone', 'event')]),
        ),
    ]
